name: "ServiceLocator CI"

on: 
  push:
    branches: 
      - main
    paths:
      - "Sources/**"
      - "Tests/**"
      - ".github/workflows/**"
      - "Package.swift"
  pull_request:
    paths:
      - "Sources/**"
      - "Tests/**"
      - ".github/workflows/**"
      - "Package.swift"

jobs:
  xcode:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - "macos-latest"
        destination:
          - 'platform=iOS Simulator,OS=15.0,name=iPhone 13'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Build and Test
        run: |
          xcodebuild test -scheme ServiceLocator -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
  spm:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
        swift:
          - "5.5"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
